version: '2.1'

services:

  cassandra:
    container_name: cassandra
    image: cassandra
    ports:
      - 9042:9042
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5

  fakemail:
    container_name: fakemail
    image: djfarrelly/maildev
    ports:
      - 1080:80
      - 25:25

  spring_weather_service:
    build: .
    ports:
      - 8080:8080
    links:
      - cassandra
      - fakemail
    depends_on:
      cassandra:
        condition: service_healthy